<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Frontend_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
<div id="menu">
    <ul style="float: left;">
        <li><a href="/">Home</a> |</li>
        <li><a href="/blog">Blog</a> |</li>
        <li><a href="/access/user/logout">Log Out</a> |</li>
    </ul>
    <div style="float: right;">
        Welcome, Guest!
    </div>
</div>
