<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Admin_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
        <div id="wrapper">
            <div id="header">
                <div id="status_bar">
                    <a href="/">View Site</a> |
                    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                        <a href="/admin/auth/logout">Log Out</a>
                    <?php else: ?>
                        <a href="/admin/auth/login">Log In</a>
                    <?php endif; ?>
                    <span style="float: right; padding-right: 15px;">
                        Advanced Website Environment
                    </span>
                </div>
            </div>
            <div id="headerShadow"> </div>
            <div id="page">
                <!--
                <div class="status_msg">
                    Everything is awesomes
                </div>
                <div class="error_msg">
                    Oh noes! ERROR: [8400]
                </div>
                -->
