<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Admin_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<?php
    $dijitTheme = 'soria';

    $title = $this->layout()->title;
    $this->headTitle(($title ? "$title - " : 'Admin - ') .  "AWE");

    $skinFolder = '/skin/admin/default';
    $this->headLink()->prependStylesheet("$skinFolder/css/layout.css");
    $this->headLink()->prependStylesheet("$skinFolder/css/styles.css");

    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    echo $this->doctype('XHTML1_TRANSITIONAL');
?>

<html dir="ltr">
    <head>
        <?php
            echo $this->headTitle(),"\n";
            echo $this->headMeta(),"\n";
            echo $this->headLink(),"\n";

            # Dojo Toolkit
            $dojoBodyClass = '';
            if ($this->dojo()->isEnabled()) {
                $dojoBodyClass = " class=\"$dijitTheme\"";
                $this->dojo()
                     ->setLocalPath("/js/release/dojo/dojo.js")
                     ->addLayer("/js/release/dojo/awedojo.js")
                     ->setDjConfigOption('dojoBlankHtmlUrl', '/js/dojo/release/dojo/dojo/resources/blank.html')
                     ->addStyleSheetModule('dijit.themes.'.$dijitTheme)
                     ->setDjConfigOption('parseOnLoad', true);

                echo $this->dojo(),"\n";
            }

            # jQuery
            if ($this->jQuery()->isEnabled()) {
                //$this->jQuery()->setLocalPath('/js/jquery/jquery-1.5.1rc1.js');
                //$this->jQuery()->setLocalPath('/js/jquery/jquery-1.4.4.min.js');
                $this->jQuery()->setLocalPath('/js/jquery/jquery-1.4.2.min.js');
                $this->jQuery()->setUiLocalPath('/js/jquery/jquery-ui-1.8.9.custom.min.js');
                $this->jQuery()->addStylesheet('/js/jquery/css/redmond/jquery-ui-1.8.9.custom.css');

                echo $this->jQuery();
            }

            echo $this->headScript(),"\n";
            echo $this->headStyle(),"\n";
        ?>
        <link rel="shortcut icon" href="/admin_favicon.ico" />
    </head>
    <body<?php echo $dojoBodyClass ?>>
        <?php echo $this->partial("_header.phtml"); ?>
        <table id="admin_columns">
            <tr>
                <td id="left_col">
                    <div id="menu_container">
                        <?= $this->partial("_menu.phtml"); ?>
                    </div>
                </td>
                <td id="right_col">
                    <?php echo $this->layout()->content; ?>
                    <?php echo $this->inlineScript(); ?>
                </td>
            </tr>
        </table>
        <?php echo $this->partial("_footer.phtml"); ?>
    </body>
</html>
