<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Admin_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<?php
    $dijit_theme = 'soria';

    $title = $this->layout()->title;
    $this->headTitle(($title ? "$title - " : 'Admin - ') .  "AWE");

    $skin_folder = '/skin/admin/default';
    $this->headLink()->prependStylesheet("$skin_folder/css/layout.css");
    $this->headLink()->prependStylesheet("$skin_folder/css/styles.css");

    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    echo $this->doctype('XHTML1_TRANSITIONAL');
?>

<html dir="ltr">
    <head>
        <?php
            echo $this->headTitle(),"\n";
            echo $this->headMeta(),"\n";
            echo $this->headLink(),"\n";
            if ($this->dojo()->isEnabled()) {
                $this->dojo()
                     ->setLocalPath("$skin_folder/js/dojo/dojo/dojo.js")
                     ->addStyleSheetModule('dijit.themes.'.$dijit_theme)
                     ->setDjConfigOption('parseOnLoad', true)
                     ;
                echo $this->dojo(),"\n";
            }
            echo $this->headScript(),"\n";
            echo $this->headStyle(),"\n";
            //echo $this->jQuery();
        ?>
        <link rel="shortcut icon" href="/admin_favicon.ico" />
    </head>
    <body class="<?= $dijit_theme; ?>">
        <?= $this->partial("_header.phtml"); ?>
        <table id="admin_columns">
            <tr>
                <td id="left_col">
                    <div id="menu_container">
                        <?= $this->partial("_menu.phtml"); ?>
                    </div>
                </td>
                <td id="right_col">
                    <?php echo $this->layout()->content; ?>
                    <?php echo $this->inlineScript(); ?>
                </td>
            </tr>
        </table>
        <?= $this->partial("_footer.phtml"); ?>
    </body>
</html>


