<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EntitiesCmsWidgetProxy extends \Entities\Cms\Widget implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function updated()
    {
        $this->_load();
        return parent::updated();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function __set($key, $val)
    {
        $this->_load();
        return parent::__set($key, $val);
    }

    public function __call($name, $args)
    {
        $this->_load();
        return parent::__call($name, $args);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'title', 'entity_name', 'template_file', 'dql_query', 'max_results', 'order_by', 'pages', 'created_at', 'updated_at');
    }
}