<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Admin_Autocrud
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<?php global $gANNOTATION_KEYS; extract($gANNOTATION_KEYS); ?>

<h1><?= $this->entity_label_plural; ?><a class="awe-grid-new-link awe-grid-action-link" href="/admin/<?= $this->controller_name; ?>/edit/">NEW</a></h1>

<table class="awe-grid">
    <tr>
        <? foreach ($this->columns as $def): ?>
            <? $anno = $def['annotations']; ?>
            <? if (isset($anno[$a_col]) && isset($anno[$a_awe])): ?>
                <? if (is_null($anno[$a_awe]->no_list)): ?>
                <? $label = $anno[$a_awe]->list_label ? $anno[$a_awe]->list_label : $anno[$a_awe]->label ? $anno[$a_awe]->label : ucwords(str_replace('_', ' ', preg_replace('[^a-zA-Z0-9_]','', (isset($anno[$a_col]) && $anno[$a_col]->name ? $anno[$a_col]->name : $property_name)))); ?>
                <th><?= $label; ?></th>
                <? endif; ?>
            <? endif; ?>
        <? endforeach; ?>
        <th class="awe-grid-action-column">Actions</th>
    </tr>
    <? $x = 0; foreach($this->entities as $entity): ?>
    <tr class="<?= ($x++ % 2 ? 'alt' : ''); ?>">
        <? foreach ($this->columns as $def): ?>
            <? $anno = $def['annotations']; ?>
            <? if (isset($anno[$a_col]) && isset($anno[$a_awe])): ?>
                <? if (is_null($anno[$a_awe]->no_list)): ?>
                    <? $column = $anno[$a_col]->name ?>
                    <? $type   = $anno[$a_col]->type ?>

                    <? if ($type == 'datetime'): ?>
                        <td><?= $entity->$column->format('m/d/Y'); ?></td>
                    <? else: ?>
                        <td><?= $entity->$column; ?></td>
                    <? endif; ?>

                <? endif; ?>
            <? endif; ?>
        <? endforeach; ?>
        <td class="awe-grid-actions">
            <a class="awe-grid-edit-link awe-grid-action-link" href="/admin/<?= $this->controller_name; ?>/edit/id/<?= $entity->id; ?>">EDIT</a>
            <a class="awe-grid-delete-link awe-grid-action-link" href="/admin/<?= $this->controller_name; ?>/delete/id/<?= $entity->id; ?>">DELETE</a>
        </td>
    </tr>
    <? endforeach; ?>
</table>
