<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Admin
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<h1>AweCMS Admin</h1>
<p style="font-weight: bold;">
Hello, and welcome to the AweCMS control panel.
</p>
<p>
To get started, choose a menu item from the left.<br/>
We suggest starting with the CMS.
</p>
<?php echo $this->foo; ?>
