<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Admin_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<h3>Design</h3>
<ul>
    <li> <a href="/admin/core_design_layout/">Layouts</a> </li>
    <li> <a href="/admin/core_design_layoutcontainer/">Layout Containers</a> </li>
    <li> <a href="/admin/core_design_widgetset/">Widget Sets</a> </li>
    <li> <a href="/admin/core_design_widgetsetmember/">Widget Set Members</a> </li>
    <li> <a href="/admin/core_design_widget/">Widgets</a> </li>
</ul>
<h3>CMS</h3>
<ul>
    <li> <a href="/admin/core_cms_page/">Pages</a> </li>
    <li> <a href="/admin/core_cms_pagewidget/">Page Widgets</a> </li>
    <li> <a href="/admin/core_cms_widget/">Widgets</a> </li>
</ul>
<h3>Blog</h3>
<ul>
    <li> <a href="/admin/core_blog_entry/">Entries</a> </li>
    <li> <a href="/admin/core_blog_comment/">Comments</a> </li>
</ul>
<h3>Access</h3>
<ul>
    <li> <a href="/admin/core_access_user/">Users</a> </li>
    <li> <a href="/admin/core_access_group/">Group</a> </li>
</ul>
<h3>Premium</h3>
<ul>
    <li> <a href="/admin/core_premium_plan/">Plan</a> </li>
    <li> <a href="/admin/core_premium_subscription/">Subscription</a> </li>
</ul>
