<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<h1>Welcome To AweCMS</h1>
<h2>It Works!</h2>
<p>
    Well, sort of.
</p>
<p>
    If you are seeing this page it probably means your CMS routes aren't configured properly, which is probably not what you want.
</p>
<p>
Try the <a href="/cms/page/view/">CMS controller</a> directly instead.
</p>
