<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Cms
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
<div class="blog-entry">
    <h2><?php echo $this->entry->title; ?></h2>
    <div class="blog-entry-content">
        <?php echo $this->entry->content; ?>
    </div>
    <div class="blog-entry-date">
        <?php echo $this->entry->pub_date->format('M j, Y h:ia'); ?>
    </div>
    <div class="blog-entry-comments">
        <?php foreach ($this->entry->comments as $c): ?>
            <h3><?php echo $c->title; ?></h3>
            <div class="blog-entry-content">
                <?php echo $c->content; ?>
            </div>
            <div class="blog-entry-date">
                <?php echo $c->pub_date->format('M j, Y h:ia'); ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>
