<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Frontend_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
    <div id="header">
        <div>
            <ul id="nav">
                <li class="contact"><a href="/contact">Contact Us</a></li>
                <li class="blog"><a href="/blog">Blog</a></li>
                <li class="colors"><a href="/colors">Color Ranges</a></li>
                <li class="products"><a href="/flame_retardant">Products</a></li>
                <li class="about"><a href="/about">About Us</a></li>
                <li class="home"><a href="/index">Home</a></li>
            </ul><br class="clearit" />
            <a href="/index"><img src="/skin/frontend/tintoria/images/logo.gif" alt="Tintoria Piana U.S., Inc." hspace="0" vspace="0" border="0" align="top" /></a>
        </div>
    </div>
