<? $skin_dir = '/skin/frontend/tintoria'; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>Tintoria Piana U.S., Inc.</title>
        <meta http-equiv="content-type" content="text/html;charset=utf-8" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta name="description" content="Yarn dyeing for the textile industry">
        <meta name="keywords" content="textiles, fiber stock dyers, acrylic, cotton, nylon, polyester, wool, rayon, fiber dyeing, dyer, fiber, cotton, acrylic, textiles, wool, finishing, stock dyers, dyed cotton, Cotton Dyers, cotton dyeing, Acrylic Dyers, Wool Dyers, Polyester Dyers, Nylon Dyers, Rayon Dyers, Raw Cotton Dyers, 100% Cotton Dyers, stock dyeing, stock dyed fiber, dyed acrylic, polyester, dyed polyester">
        <meta name="Excite Meta Search" content="keywords">

        <!-- 12-2-97 -->
        <!-- 1-6-98 -->
        <!-- TextileWeb. Inc --- Eric Swinson-->
        <!-- Website Name by TextileWeb.Inc -- textiles, fiber stock dyers, acrylic, cotton, nylon, polyester, wool, rayon, fiber dyeing, dyer, fiber, cotton, acrylic, textiles, wool, finishing, stock dyers, dyed cotton, Cotton Dyers, cotton dyeing, Acrylic Dyers, Wool Dyers, Polyester Dyers, Nylon Dyers, Rayon Dyers, Raw Cotton Dyers, 100% Cotton Dyers, stock dyeing, stock dyed fiber, dyed acrylic, polyester, dyed polyester -->
        <!-- Website Name by TextileWeb.Inc -- textiles, fiber stock dyers, acrylic, cotton, nylon, polyester, wool, rayon, fiber dyeing, dyer, fiber, cotton, acrylic, textiles, wool, finishing, stock dyers, dyed cotton, Cotton Dyers, cotton dyeing, Acrylic Dyers, Wool Dyers, Polyester Dyers, Nylon Dyers, Rayon Dyers, Raw Cotton Dyers, 100% Cotton Dyers, stock dyeing, stock dyed fiber, dyed acrylic, polyester, dyed polyester -->
        <!-- Website Name by TextileWeb.Inc -- textiles, fiber stock dyers, acrylic, cotton, nylon, polyester, wool, rayon, fiber dyeing, dyer, fiber, cotton, acrylic, textiles, wool, finishing, stock dyers, dyed cotton, Cotton Dyers, cotton dyeing, Acrylic Dyers, Wool Dyers, Polyester Dyers, Nylon Dyers, Rayon Dyers, Raw Cotton Dyers, 100% Cotton Dyers, stock dyeing, stock dyed fiber, dyed acrylic, polyester, dyed polyester -->
        <link rel="stylesheet" type="text/css" href="<?= $skin_dir; ?>/css/style.css" />
        <!--[if IE]>
          <link rel="stylesheet" type="text/css" href="<?= $skin_dir; ?>/css/style_ie.css" />
        <![endif]-->
        <!--[if IE 6]>
          <link rel="stylesheet" type="text/css" href="<?= $skin_dir; ?>/css/style_ie6.css" />
        <![endif]-->
        <link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
        <script type="text/javascript" src="<?= $skin_dir; ?>js/prototype.js"></script>
        <script type="text/javascript" src="<?= $skin_dir; ?>js/scriptaculous.js?load=effects"></script>
        <script type="text/javascript" src="<?= $skin_dir; ?>js/lightbox.js"></script>
        <script language="javascript">AC_FL_RunContent = 0;</script>
        <script src="<?= $skin_dir; ?>AC_RunActiveContent.js" language="javascript"></script>
    </head>
    <body>
        <?= $this->partial('_header.phtml'); ?>
        <div id="outer">
            <?= $this->layout()->content; ?>

            <?= $this->partial('_footer.phtml'); ?>
        </div>
    </body>
</html>
