<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Cms
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<? $children = $this->children; ?>
<? if($children->count()): ?>
<ul>
    <? foreach($children as $child): ?>
        <li><a href="<?= $child->getUrl(); ?>"><?= $child->title; ?></a></li>
    <? endforeach; ?>
</ul>
<? endif; ?>
