<h3>Tags</h3>
<ul>
    <li><a href="/blog/tags/amazon/" style="font-size: 8pt;">Amazon</a> </li>
    <li><a href="/blog/tags/apache/" style="font-size: 12.666666666667pt;">Apache</a> </li>
    <li><a href="/blog/tags/architecture/" style="font-size: 14.222222222222pt;">Architecture</a> </li>
    <li><a href="/blog/tags/autocrud/" style="font-size: 10.8pt;">Autocrud</a> </li>
    <li><a href="/blog/tags/bootstrap/" style="font-size: 8pt;">Bootstrap</a> </li>
    <li><a href="/blog/tags/configuration/" style="font-size: 17.333333333333pt;">Configuration</a> </li>
    <li><a href="/blog/tags/couchdb/" style="font-size: 8pt;">CouchDB</a> </li>
    <li><a href="/blog/tags/django/" style="font-size: 14.222222222222pt;">Django</a> </li>
    <li><a href="/blog/tags/doctrine/" style="font-size: 18.888888888889pt;">Doctrine</a> </li>
    <li><a href="/blog/tags/erlang/" style="font-size: 8pt;">Erlang</a> </li>
    <li><a href="/blog/tags/functional-programming/" style="font-size: 10.8pt;">Functional Programming</a> </li>
    <li><a href="/blog/tags/haskell/" style="font-size: 10.8pt;">Haskell</a> </li>
    <li><a href="/blog/tags/hosting/" style="font-size: 8pt;">Hosting</a> </li>
    <li><a href="/blog/tags/initialization/" style="font-size: 10.8pt;">Initialization</a> </li>
    <li><a href="/blog/tags/installation/" style="font-size: 10.8pt;">Installation</a> </li>
    <li><a href="/blog/tags/irc/" style="font-size: 10.8pt;">IRC</a> </li>
    <li><a href="/blog/tags/jazz/" style="font-size: 8pt;">Jazz</a> </li>
    <li><a href="/blog/tags/memory/" style="font-size: 8pt;">Memory</a> </li>
    <li><a href="/blog/tags/mongodb/" style="font-size: 8pt;">MongoDB</a> </li>
    <li><a href="/blog/tags/musicians/" style="font-size: 8pt;">Musicians</a> </li>
    <li><a href="/blog/tags/mysql/" style="font-size: 8pt;">MySQL</a> </li>
    <li><a href="/blog/tags/netiquette/" style="font-size: 10.8pt;">Netiquette</a> </li>
    <li><a href="/blog/tags/newbie/" style="font-size: 10.8pt;">Newbie</a> </li>
    <li><a href="/blog/tags/nosql/" style="font-size: 8pt;">NoSQL</a> </li>
    <li><a href="/blog/tags/open-source-software/" style="font-size: 10.8pt;">Open Source Software</a> </li>
    <li><a href="/blog/tags/passenger/" style="font-size: 8pt;">Passenger</a> </li>
    <li><a href="/blog/tags/philosophy/" style="font-size: 14.222222222222pt;">Philosophy</a> </li>
    <li><a href="/blog/tags/php/" style="font-size: 18.111111111111pt;">PHP</a> </li>
    <li><a href="/blog/tags/rackspace/" style="font-size: 8pt;">Rackspace</a> </li>
    <li><a href="/blog/tags/radiant/" style="font-size: 8pt;">Radiant</a> </li>
    <li><a href="/blog/tags/rails/" style="font-size: 10.8pt;">Rails</a> </li>
    <li><a href="/blog/tags/rdbms/" style="font-size: 8pt;">RDBMS</a> </li>
    <li><a href="/blog/tags/redmine/" style="font-size: 10.8pt;">Redmine</a> </li>
    <li><a href="/blog/tags/resource/" style="font-size: 8pt;">Resource</a> </li>
    <li><a href="/blog/tags/server/" style="font-size: 8pt;">Server</a> </li>
    <li><a href="/blog/tags/setup/" style="font-size: 10.8pt;">Setup</a> </li>
    <li><a href="/blog/tags/support/" style="font-size: 10.8pt;">Support</a> </li>
    <li><a href="/blog/tags/troll/" style="font-size: 10.8pt;">Troll</a> </li>
    <li><a href="/blog/tags/tutorial/" style="font-size: 10.8pt;">Tutorial</a> </li>
    <li><a href="/blog/tags/vim/" style="font-size: 8pt;">vim</a> </li>
    <li><a href="/blog/tags/vps/" style="font-size: 8pt;">VPS</a> </li>
    <li><a href="/blog/tags/zend-framework/" style="font-size: 22pt;">Zend Framework</a> </li>
    <li><a href="/blog/tags/zend_auth/" style="font-size: 10.8pt;">Zend_Auth</a> </li>
    <li><a href="/blog/tags/zend_layout/" style="font-size: 8pt;">Zend_Layout</a> </li>
    <li><a href="/blog/tags/zend_view/" style="font-size: 8pt;">Zend_View</a></li>
</ul> 
