<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Frontend_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
<?php $breadcrumbs = $this->entities; ?>
<ul id="breadcrumbs">
    <? foreach($breadcrumbs as $crumb): ?>
    <li>&raquo; <a href="<?php echo $crumb['url']; ?>"><?php echo $crumb['title']; ?></a></li>
    <? endforeach; ?>
</ul>
