<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Frontend_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
<?php $children = $this->entities; ?>
<?php if ($children->count()): ?>
<ul>
    <?php foreach($children as $child): ?>
    <li><a href="<?php echo $child->getUrl(); ?>"><?php echo $child->title; ?></a></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
