<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Theme_Admin_Default
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>

<h3>CMS</h3>
<ul>
    <li> <a href="/admin/cms_page/">Pages</a> </li>
    <li> <a href="/admin/cms_widget/">Widgets</a> </li>
    <li> <a href="/admin/cms_pagewidget/">Page Widgets</a> </li>
</ul>
<h3>Blog</h3>
<ul>
    <li> <a href="/admin/blog_entry/">Entries</a> </li>
    <li> <a href="/admin/blog_comment/">Comments</a> </li>
</ul>
<h3>Access</h3>
<ul>
    <li> <a href="/admin/access_user/">Users</a> </li>
    <li> <a href="/admin/access_group/">Group</a> </li>
</ul>
<h3>Premium</h3>
<ul>
    <li> <a href="/admin/premium_plan/">Plan</a> </li>
    <li> <a href="/admin/premium_subscription/">Subscription</a> </li>
</ul>
