<?php
    $this->jQuery()->enable();
    $this->jQuery()->addStylesheet('/js/jquery/css/ui.jqgrid.css');
    $this->jQuery()->addJavascriptFile('/js/jquery/i18n/grid.locale-en.js');
    $this->jQuery()->addJavascriptFile('/js/jquery/jquery.jqGrid.min.js');
    $this->jQuery()->onLoadCaptureStart();
?>
$("#theGrid").jqGrid({
    caption: 'Blog Comments',
    url:'/jqgrid/core/blog/comment/list',
    colNames:['Is Approved', 'Title', 'Date Published'],
    colModel :[ 
        {name:'approved', index:'approved', width:150}, 
        {name:'title', index:'title', width:150}, 
        {name:'pub_date', index:'pub_date', width:150, align:'right'}
    ],
    datatype: 'json',
    mtype: 'GET',
    pager: '#thePager',
    rowNum: 10,
    rowList: [10,20,30]
}); 
<? $this->jQuery()->onLoadCaptureEnd(); ?>
<h1>Hello jQuery Playground</h2>
<p>
Here's some text before the container
</p>
<p>
<a id="myLink" href="http://www.apple.com/">Click Here</a>
</p>
<table id="theGrid"></table>
<div id="thePager"></div>
<p>
Here's some text after it
</p>
