<?php
/**
 * AweCMS
 *
 * LICENSE
 *
 * This source file is subject to the BSD license that is bundled
 * with this package in the file LICENSE.txt
 *
 * It is also available through the world-wide-web at this URL:
 * http://www.opensource.org/licenses/bsd-license.php
 *
 * @category   AweCMS
 * @package    AweCMS_Cms
 * @copyright  Copyright (c) 2010 Rock Solid Web Design (http://rocksolidwebdesign.com)
 * @license    http://www.opensource.org/licenses/bsd-license.php BSD License
 */
?>
<?php $entry = $this->entry; ?>
<div class="blog-entry">
    <h2><?php echo $entry->title; ?></h2>
    <div class="blog-entry-content"><?php echo $entry->content; ?></div>
    <div class="blog-entry-date">
        <?php echo $entry->pub_date->format('M j, Y h:ia'); ?>
    </div>
</div>
<div class="blog-entry-comments">
    <?php foreach ($entry->comments as $comment): ?>
        <h3><?php echo $comment->title; ?></h3>
        <div class="blog-entry-content"><?php echo $comment->content; ?></div>
        <div class="blog-entry-date">
            <?php echo $comment->pub_date->format('M j, Y h:ia'); ?>
        </div>
    <?php endforeach; ?>
</div>
